### ISSUE TITLE
IntentService-like behavior for Goro

### ISSUE THREAD

**Issue by almozavr** [stanfy/enroscar#62] opened 2015-04-02 22:34 UTC
I'm trying to use goro combined with services from out of application-scoped singletons, not bounded to ui-lifecycle. I wonder, what's the easy way to make goro (or BoundGoro) act as IntentService? Do I have to subscribe/unsubscribe on each task I produce and schedule?

**Comment by almozavr** [comment] 2015-04-02 23:13
By now, I'm doing like this: ![](http://monosnap.com/image/mjlJKzqxiwLq5zkCfVadtTWLw3HlJD.png)

**Comment by roman-mazur** [comment] 2015-04-03 06:08
Sorry if it's a too long explanation. I just decided to write it to publish somewhere later...

First of all, every `Goro` instance keeps its own queues. It means that in this code
```java
Goro goro1 = Goro.create(), goro2 = Goro.create();
goro1.schedule("network", task1)
goro2.schedule("network", task2)
```
tasks `task1` and `task2` will not be executed sequentially (they will use the same thread pool, because by default `Goro` uses thread pool of `AsyncTask`, but queues will be different).

And if you want these tasks to be executed sequentially, you need to ensure that the single `Goro` instance is used. Using `BoundGoro` is one of the ways to achieve this. Because `BoundGoro` proxies a `Goro` instance owned by a dedicated services.
As a result, when you use multiple `BoundGoro` instances, you still use one `Goro` to actually enqueue  the tasks, plus you make sure that these tasks are "guarded" by the service (since even if activities are finished, the system still knows that your process is running a service, and your processed will not be marked as an "empty" one and will not be the first candidate to kill).

Another approach is to simply use a `Goro` singleton in the application scope. You may a whatever approach you like: own it in the `Application` instance, inject with Dagger ensuring it's properly scoped.

There are some strict rules when `BoundGoro` is used.
You should ensure that you do not create more than one `BoundGoro` instance per `Context`. This is connected with the fact that the context supplied to `bindWith()` is used to perform `bindService()` invocation. This binding creates a connection between the context you use and the service that owns the `Goro` instance. And you are not allowed to create more than one such a connection (Android system will say you leak a connection and you will crash). So basically you can call `bindService` on one context twice binding to the same service.

Hence, there must be one instance of `BoundGoro` per context: they must be context scoped.
A pattern for an Activity:
``javaj
class MyActivity extends Activity {
  final BoundGoro goro = BoundGoro.bindWith(this);

  protected void onStart() { goro.bind(); }
  protected void onStop() { goro.unbind(); }
}
``
Note that you should not create a `BoundGoro` instance in fragments. Instead inject then into the fragments taking the instance from the activity.

A pattern for a `Service`:
```java
class MyService extends Service {
  final BoundGoro goro = BoundGoro.bindWith(this);
  protected void onCreate() { goro.bind(); }
  protected void onDestroy() { goro.unbind(); }
}
```

We often use this service pattern for `SyncAdapter`s. The goro instance is created in the service, then passed to the sync adapter, and the sync adapter can use `RxGoro` to paralelize some processes and enqueue sub-tasks properly.
A sync service binding to another (`GoroService`) might sound as an overkill. But when it's combined with a task started from some UI context, which does a database write and uses the same queue that is used by the sync adapter for db updates, it might start to make sense :)

I hope this helps. And basically in your example doing
```java
Goro.bindWith(someContext).bind();
```
in your `GoroObservable` class is not the right thing. Bind and unbind calls on `BoundGoro` should be coupled with the used context lifecycle. 

P.S. There is also `bindOneShot()` method in `BoundGoro` interface. We used it start some async tasks from `Application.onCreate()`: use `Application` context to bind to the service, do staff, unbind as soon as this staff is finished. But you must rather careful this this approach. It usually creates more problems than solves.

**Comment by roman-mazur** [comment] 2015-04-03 06:13
Sorry for typos. I corrected the previous comment.

**Comment by almozavr** [comment] 2015-04-03 08:42
This is a *great* explanation, I'm afraid I haven't got it all from sources.
As I mentioned, my aim is yes, to use goro for `IntentService` like jobs - when there is a queue, service should be running and when jobs are finished, service should be closed. Also let's assume one uses only `app-scoped` Context, so service life should not be bound to context's lifecycle.

I see, my prev. approach won't work for many `BoundGoro`-to-one-`context`, so despite your advice not to use `bindOneShot()`, I tried and got nearly expected result: service starts, queue tag is honored, service shutdowns gracefully when no task left to do:

```java
public static <T> Observable<T> onService(Context context, String queue, Callable<T> callable) {
    BoundGoro goro = Goro.bindWith(context);
    goro.bindOneshot();
    return new RxGoro(goro)
            .schedule(queue, callable);
}
```

```java
    private Job1Executor<LoginData, Session> buildLoginExecutor() {
        return new Job1Executor<>((data) -> {
            Observable<Void> preSessionObservable = GoroObservable.onService(context, "network", () -> {
                        Timber.d("Starting pre-session request");
                        Thread.sleep(TimeUnit.SECONDS.toMillis(10));
                        return null;
                    }
            );
            Observable<Session> sessionObservable = GoroObservable.onService(context, "network", () -> {
                Timber.d("Starting session request");
                Thread.sleep(TimeUnit.SECONDS.toMillis(15));
                if (data.username().equalsIgnoreCase("me") && data.password().equals("qwe")) {
                    return (Session) ImmutableSession.builder().accountId(1).build();
                }
                throw new IllegalArgumentException("Wrong params");
            }).doOnNext(session -> {
                Timber.d("Logged in with session %s", session);
                prefs.storeObjectAsGson(Session.class.getName(), session, false);
            });
            return Observable.zip(
                    preSessionObservable,
                    sessionObservable,
                    (Void, session) -> session
            );
        });
    }
```

```
11:22:22.505  D/JobExecutor﹕ Job started
11:22:22.635  D/SessionManager﹕ Starting pre-session request
11:22:32.640  D/SessionManager﹕ Starting session request
11:22:47.655  D/SessionManager﹕ Logged in with session Session{accountId=1,active=true}
11:22:47.755  D/JobExecutor﹕ Job finished:Job{status=SUCCESS,value=Session{accountId=1,active=true},error=null}
```

So I wonder, what problems could be produced by this method?

**Comment by roman-mazur** [comment] 2015-04-03 14:32
With current implementation of `bindOneShot` this approach is not really safe.
When `bindOneShot` is invoked, we call `bindService` on the context. *Later* `BoundGoro` will receive a connection to the service. When this connection is established, scheduled tasks will be passed to the service and `unbind` will be called automatically.
The problem is that between the moments you call `bindOneShot` and connection is established you can call `bindOneShot` again, which will cause 2 invocations of `bindService` on the context in a row.
`BoundGoro` tries to bind every time `bindOneShot` is called.
We have used this only in `Applciation.onCreate`, which is called only once in the application process lifecycle. Hence, it's safe there, but not in you case.

**Comment by roman-mazur** [comment] 2015-06-20 23:52
Goro is moved to a separate repo. https://github.com/stanfy/goro

**Closed by roman-mazur** 2015-06-20 23:52 UTC
